### ISSUE TITLE
Issue with UVC convergence

### ISSUE THREAD

**Issue by Diegohere** [ahartloper/UVC_MatMod#9]
When I try to run the OpenSees test file for the 3b_brick using the following material parameters: nDMaterial UVCmultiaxial 1 185970.0 0.3 332.18 120.48 8.14 93.15 261.75 2 21102.0 173.6 2300.6 10.42, the code diverges the first time the reverse mapping procedure is used.

**Comment by ahartloper** [comment]
Can you try running the same test file with the displacement control integrator?

I added additional validation in e102d1a that implies the results from the original file 3d_brick agree with Abaqus to 10^-7 relative error.

I have a feeling that in force control the Newton method cannot converge when the tangent becomes close to zero. Otherwise, there could be a bug when using the DInf and a parameters.
